### ISSUE TITLE
Version 0.8.3 hangs

### ISSUE THREAD

**Issue by cazzer** [jonschlinkert/extract-comments#6] opened 2015-11-03 23:28 UTC
Some part of the quoted string change broke this module for me. I'm digging through for the issue now but I wanted to bring it to your attention in case I can't find it quickly.

Version `0.8.2` works fine for me.

**Comment by jonschlinkert** [comment] 2015-11-03 23:30
thanks for letting me know, I'll look into it asap

**Comment by jonschlinkert** [comment] 2015-11-03 23:33
I think know where the problem is. It will be somewhere in the quoted-string logic either:
- here: https://github.com/jonschlinkert/extract-comments/blob/master/index.js#L136-L144, or
- here: https://github.com/jonschlinkert/extract-comments/blob/master/index.js#L59-L78

I'm looking now, but in case you see the issue before me

**Comment by jonschlinkert** [comment] 2015-11-03 23:40
ah, I know what to do. Right now it's detecting if a comment is inside a quoted string, and if so it skips the comment and starts off where it ends - but it should be starting off where the quoted string ends.

**Comment by cazzer** [comment] 2015-11-03 23:42
Quick catch, thanks for responding so fast. Let me know if I can help test.

**Comment by jonschlinkert** [comment] 2015-11-03 23:49
> Let me know if I can help test.

that would be great, thanks. if you know what pattern was causing it to hang, Ideally you could add a unit test with that pattern, but no worries 

let me know if this did the trick. thanks!

**Comment by jonschlinkert** [comment] 2015-11-03 23:51
oh, and fwiw I was wrong in [this comment](https://github.com/jonschlinkert/extract-comments/issues/6#issuecomment-153525285), it just needed to break out of the loop when we reached the end of the string, and the logic for that wasn't correct. I _think_ it's right now

**Comment by cazzer** [comment] 2015-11-04 00:03
Hmm, that did fix the module from hanging but I'm getting a different output than in the previous version (and I don't have any quoted comments in the file I'm processing). Now that the tests pass and its not hanging I'll send a PR with a test to replicate my issue.

**Comment by jonschlinkert** [comment] 2015-11-04 00:08
I did find a pattern that hangs, same issue though. the unit test would be great, thanks. I'm going to try to see what's happening and report back

**Comment by cazzer** [comment] 2015-11-04 00:44
I opened #7, which covers a quote issue, (just a test). I think it is technically a new issue now though: comments after quoted strings are missed.

**Comment by jonschlinkert** [comment] 2015-11-04 08:51
I just pushed up some changes. should be fixed but let me know if you have any more issues.

**Closed as completed by jonschlinkert** 2015-11-04 08:51 UTC
Labels: bug
